fix: Alphabetized API Structures sidebar
electron/website pull request #422
Opened 2023-06-27 09:52 UTC by abhishekgite446

Fixing the [Issue 408](https://github.com/electron/website/issues/408)

Alphabetized API Structures sidebar ✅

2023-06-27 12:50 UTC, ChavvaNarayana reviewed
It is not considered the correct approach.

2023-06-27 20:12 UTC, abhishekgite446 commented
Retrieved the hardcoded changes made in the first commit and added a function to sort the sidebar sub-elements in [API tab](https://www.electronjs.org/docs/latest/api/app).


https://github.com/electron/website/assets/253690/fd383962-c553-44a5-95c0-49e18e7df946

2023-06-28 06:54 UTC, dsanders11 requested changes
`sidebars.js` is generated by [`scripts/tasks/create-sidebar.ts`](https://github.com/electron/website/blob/main/scripts/tasks/create-sidebar.ts), so it is not the correct place to put these changes.

2023-06-29 18:52 UTC, abhishekgite446 commented
Hi @dsanders11, thanks for letting me know. I was having a look at the file [scripts/tasks/create-sidebar.ts](https://github.com/electron/website/blob/main/scripts/tasks/create-sidebar.ts) and observed that when I disabled/commented out the **if condition** mentioned below in the same file and executed the command `yarn pre-build `then the [sidebar.js](https://github.com/electron/website/blob/main/sidebars.js) was overwritten with 'API Structures' sorted in alphabetical array. 

I reverted my changes from [scripts/tasks/create-sidebar.ts](https://github.com/electron/website/blob/main/scripts/tasks/create-sidebar.ts) as the sidebar.js is already sorted and going ahead if a new api is added in the folder [docs/latest/api/structures](https://github.com/electron/website/tree/main/docs/latest/api/structures) then the` yarn pre-build` command should add that in [sidebar.js](https://github.com/electron/website/blob/main/sidebars.js) in sorted order.

Would love to know your thoughts on it.
![image](https://github.com/electron/website/assets/253690/b9ba7cbb-d80d-4691-99b4-371ae7de5bc8)

2025-01-21 17:31 UTC, closed without merging