feat: tabbed CJS/ESM code blocks
electron/website pull request #488
Opened 2023-12-18 09:32 UTC by dsanders11

Combines back-to-back code blocks with language identifiers of CJS followed by MJS into tabbed code blocks. Code blocks can opt-out by adding `no-combine` to the meta string for the code block. Also optionally strips a preamble comment in the code blocks (making them more user-friendly in rendered Markdown not on the website).

No upstream usage in the docs yet. Will add linting on `e/e` to enforce certain things (like the preamble comments).

2024-01-02 01:45 UTC, BlackHole1 requested changes

2024-01-02 01:45 UTC, BlackHole1 commented on src/components/ESMCodeBlock.tsx
This file contains the handling logic for both esm and cjs, but the file name only reflects esm, which may confuse other maintainers. Perhaps we can change it to: `JSCodeBlock.tsx`

2024-01-02 01:45 UTC, BlackHole1 commented on src/transformers/esm-code-blocks.ts
Same as above

2024-01-12 19:12 UTC, erickzhao approved these changes
Agree with @BlackHole1 but otherwise LGTM. Can we also make a demo/playground to give it a spin?

2024-01-14 03:43 UTC, dsanders11 commented
Renamed files per suggestion and added a demo page (will remove before merge) at `/docs/latest/tabbed-js-code-block/`, [here's the deployed preview.](https://electronjsorg-new-pr-488.herokuapp.com/docs/latest/tabbed-js-code-block/)

2024-01-15 01:59 UTC, BlackHole1 approved these changes
LGTM

2024-01-16 23:51 UTC, erickzhao approved these changes

2024-01-17 00:11 UTC, merged