fix: add width css to .navbar__logo to avoid layout change during theme change
electron/website pull request #543
Opened 2024-03-27 01:30 UTC by JasonFengGit

Resolving https://github.com/electron/website/issues/539.

Current Behavior: the logo still blinks sometimes when changing theme, but the layout would not be messed up. This is the same behavior as https://docusaurus.io/docs

Built and tested on my local environment (windows, chrome) with different window sizes.

Related: https://github.com/facebook/docusaurus/issues/8188

2024-03-27 02:02 UTC, BlackHole1 requested changes

2024-03-27 02:02 UTC, BlackHole1 commented on src/css/custom.scss
> +}
```suggestion
}

```

2024-03-27 02:02 UTC, BlackHole1 commented on src/css/custom.scss
> +// avoid layout change during theme change
```suggestion
// fix https://github.com/electron/website/issues/539
```

2024-03-27 04:30 UTC, JasonFengGit commented
Hi @BlackHole1, I have applied the requested changes. Thank you so much for the suggestions!

2024-03-27 04:31 UTC, BlackHole1 approved these changes
LGTM

2024-03-28 19:24 UTC, dsanders11 approved these changes

2024-03-28 19:24 UTC, merged