docs: ecosystem node 22 update blog
electron/website pull request #698
Opened 2024-12-02 22:48 UTC by VerteDinde

This PR adds a blog/announcement for our plan to move the ecosystem packages to Node 22

2024-12-02 23:27 UTC, erickzhao requested changes

2024-12-02 23:27 UTC, erickzhao commented on blog/node-22-ecosystem-update.md
> +In early 2025, Electron’s npm ecosystem repos (under the `@electron/` and `@electron-forge/` namespaces) will move to Node.js 22 as the minimum supported version.
```suggestion
```

This is duplicated in the rendered version, so let's just remove it.

2024-12-02 23:27 UTC, erickzhao commented on blog/node-22-ecosystem-update.md
> +Additionally, newer versions of Node.js have included many improvements that we would like to leverage, such as runtime-native common utilities (e.g. `fs.glob` and `util.parseArgs`) and entire new ba
```suggestion
Additionally, newer versions of Node.js have included many improvements that we would like to leverage, such as runtime-native common utilities (e.g. [`fs.glob`](https://nodejs.org/api/fs.html#fsglobpattern-options-callback) and [`util.parseArgs`](https://nodejs.org/api/util.html#utilparseargsconfig)) and entire new batteries-included modules (e.g. [`node:test`](https://nodejs.org/api/test.html), [`node:sqlite`](https://nodejs.org/api/sqlite.html)).
```

Reading over this, I think adding links would be a good enhancement

2024-12-03 00:32 UTC, nikwen commented
Looks good to me! :+1:

2024-12-03 01:27 UTC, ckerr commented on blog/node-22-ecosystem-update.md
> +Over time, maintenance of this policy has become increasingly difficult for a few reasons:
This phrasing "maintenance of this policy" is a little confusing about whether the _version_ is changing (a one-time bump) or whether the _policy_ is changing too (such as, more frequent bumps in the future)

If it's the latter, then we should be a lot more explicit about it here. If it's the former, I'd rephrase:

```suggestion
Over time, using Node.js 14 as our minimum version has become increasingly difficult for a few reasons:
```

2024-12-03 01:27 UTC, ckerr commented on blog/node-22-ecosystem-update.md
> +Additionally, newer versions of Node.js have included many improvements that we would like to leverage, such as runtime-native common utilities (e.g. [`fs.glob`](https://nodejs.org/api/fs.html#fsglob
I'm not sure about this one, but should this paragraph be a third bullet point in the previous list? Fits the rule of three

2024-12-03 01:27 UTC, ckerr commented on blog/node-22-ecosystem-update.md
> +Note that the Node version running in your project is unrelated to the Node version embedded into your current version of Electron.
This is a good start but I'd go even further, e.g.  explaining if your app uses  Node 21 but doesn't use any ecosystem apps, they don't need to make any changes (I think?)

2025-01-06 20:31 UTC, ckerr approved these changes

2025-01-06 20:44 UTC, erickzhao approved these changes
:shipit:

2025-01-07 18:36 UTC, merged